<?php

return [
    'title' => 'Changelog',
    'desc' => 'This page records not only major changes happened to my websites, but also changes about myself. I hope this journey is never going to end.',
    'website' => '<em>zhen-chen.com</em> is built based on popular framework <a href="https://laravel.com/">Laravel</a> using <a href="https://php.net/">PHP</a>7 and <a href="https://www.mysql.com/">MySQL</a> database while <em>blog.zhen-chen.com</em> is a fully static site generated by <a href="https://jekyllrb.com/">Jekyll</a>. <em>zhen-chen.com</em> also uses fancy <a href="https://github.com/defunkt/jquery-pjax">pjax</a> technology to give you a smooth experience. All my websites are hosted on droplets from <a href="https://m.do.co/c/abfc6e767656">DigitalOcean</a> and served to you through <a href="https://www.cloudflare.com/">CloudFlare</a> CDN service. They all use <a href="http://nginx.org/">Nginx</a> as the back-end server with <a href="https://developers.google.com/speed/pagespeed/module/">PageSpeed Module</a> to achieve content optimization. My server uses <a href="https://en.wikipedia.org/wiki/HTTPS">HTTPS</a> with <a href="https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security">HSTS</a> to enhance transmission security and <a href="https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions">DNSSEC</a> is also enabled to secure domain name translation. My server also supports <a href="https://en.wikipedia.org/wiki/IPv6">IPv6</a> and <a href="https://en.wikipedia.org/wiki/HTTP/2">HTTP/2</a>.',

    '2013_05' => '<li>Bought domain <em>rainbow-chen.com</em>.</li>',
    '2013_07' => '<li>Touched <em>HTML</em>, <em>CSS</em>, <em>Javascript</em>, and <em>PHP</em> for the first time.</li>',
    '2013_11' => '<li>Attended IELTS test. It was a nightmare. Luckily, it seemed that I only need to attend it once in my life.</li><li>Personal website 1.0 published built using basic <em>PHP</em> and hosted on a shared hosting service.</li>',
    '2013_12' => '<li>Joined Jianjia Chinese Localization Group.</li><li>Received offer for Bachelor of Engineering (Honours) from the <a href="https://www.auckland.ac.nz/">University of Auckland</a>.</li><li>Received offer for Bachelor of Science in Computer Science and Information System from the <a href="https://www.auckland.ac.nz/">University of Auckland</a>. Accepted.</li>',

    '2014_01' => '<li>Blog published built using <em>WordPress</em>.</li>',
    '2014_02' => '<li>Arrived in New Zealand, a beautiful and fascinating country.</li>',
    '2014_03' => '<li>Started studying Computer Science and Information System at the <a href="https://www.auckland.ac.nz/">University of Auckland</a>.</li>',
    '2014_09' => '<li>Comments enabled.</li>',
    '2014_11' => '<li>Made simple back-end system for Wechat public account of the Industrial Bank Shanghai Changning Branch. <a href="https://github.com/ad52825196/wechat-xingyechangning">#</a></li>',
    '2014_12' => '<li>Bought domain <em>rainbow-chen.xyz</em>.</li>',

    '2015_02' => '<li>Became a UniGuide at the <a href="https://www.auckland.ac.nz/">University of Auckland</a>.</li>',
    '2015_03' => '<li>Participated in Round the Bays long run activity.</li>',
    '2015_06' => '<li>Learned how to use API for the first time and made a simple program to get tweets from Twitter API. <a href="https://github.com/ad52825196/twitter">#</a></li>',
    '2015_08' => '<li>Tried to use a VPS server for the first time.</li>',
    '2015_09' => '<li>Server seedbox downloading deployed.</li><li>Nice to-top button enabled.</li>',
    '2015_11' => '<li>Personal website moved to my VPS server.</li><li>Started using <em>Nginx</em> with <em>PageSpeed Module</em>.</li>',
    '2015_12' => '<li><em>IPv6</em> enabled.</li><li><em>HTTPS</em> enabled.</li><li><em>HTTP/2</em> enabled.</li>',

    '2016_01' => '<li>Deprecated domain <em>rainbow-chen.com</em>.</li><li>Deprecated domain <em>rainbow-chen.xyz</em>.</li><li>Bought domain <em>zhen-chen.com</em>.</li><li>Bought domain <em>zhen-chen.xyz</em>.</li>',
    '2016_03' => '<li>Became a Teaching Assistant at the <a href="https://www.auckland.ac.nz/">University of Auckland</a>.</li>',
    '2016_04' => '<li>Touched and started studying <em>Laravel</em> by myself.</li><li>Personal website 2.0 published built using basic <em>Laravel</em> and <em>PHP</em>7.</li>',
    '2016_08' => '<li>Tried Unity engine for the first time.</li>',
    '2016_12' => '<li>Won Best BSc in Information System Award.</li><li><em>DNSSEC</em> enabled.</li><li><em>HSTS</em> enabled.</li><li>Rainbow Shadowsocks went alive. <a href="https://ss.zhen-chen.xyz">#</a></li>',

    '2017_02' => '<li>Rainbow Studio went alive. <a href="https://zhen-chen.xyz">#</a></li><li>Won Senior Scholar Award in the Faculty of Science.</li>',
    '2017_03' => '<li>Personal website 3.0 published built using <em>Laravel</em> with <em>pjax</em>.</li>',
    '2017_05' => '<li>Graduated with a Bachelor of Science Degree in Computer Science and Information System from the <a href="https://www.auckland.ac.nz/">University of Auckland</a>.</li>',
];
